service: paraphraser
# app and org for use with dashboard.serverless.com
app: paraphraser-rss
#org: your-org-name
custom:
  dynamoSourceMetaTableName: 'SourceMeta-${sls:stage}'
  sourceStepFunctionName: 'SourceStep-${sls:stage}'
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    SOURCE_META_TABLE: ${self:custom.dynamoSourceMetaTableName}
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:BatchWriteItem
        Resource:
          - { "Fn::GetAtt": ["DynamoSourceMeta", "Arn" ] }

plugins:
  - serverless-plugin-include-dependencies
  - serverless-step-functions
functions:
  generateBBCMeta:
    handler: generator/sources/rss/bbc/bbc.getMeta
  filterForDynamo:
    handler: generator/source-db-filter.filter
  transformForDynamo:
    handler: generator/source-db-transform.dynamo
  batchWriteToDynamo:
    handler: generator/source-db-write.dynamo
stepFunctions:
  stateMachines:
    paraphraser:
      name: ${self:custom.sourceStepFunctionName}
      definition:
        Comment: 'Gather new source documents to paraphrase into articles'
        StartAt: ConsumeRSSFeeds
        States:
          ConsumeRSSFeeds:
            Type: Parallel
            Branches:
              - StartAt: Pass
                States:
                  Pass:
                    Type: Pass
                    End: true
              - StartAt: BBC
                States:
                  BBC:
                    Type: Task
                    Resource:
                      Fn::GetAtt: [generateBBCMeta, Arn]                    
                    Next: DynamoTransform
                  DynamoTransform:
                    Type: Task
                    Resource:
                      Fn::GetAtt: [transformForDynamo, Arn]                    
                    Next: DynamoBatchWrite
                  DynamoBatchWrite:
                    Type: Task
                    Resource:
                      Fn::GetAtt: [batchWriteToDynamo, Arn]                    
                    End: true
            End: true
resources:
  Resources:
    DynamoSourceMeta:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamoSourceMetaTableName}
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
          - AttributeName: link
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        Tags:
          - 
            Key: Paraphraser
            Value: Paraphraser
        GlobalSecondaryIndexes:
          - IndexName: linkIndex
            KeySchema:
              - AttributeName: link
                KeyType: HASH
            Projection:
              ProjectionType: ALL
outputs:
  NewOutput:
    Description: "Description for the output"
    Value: "Some output value"
